# ANÁLISE DAS OCORRÊNCIAS DA LEI MARIA DA PENHA NO ESTADO DO CEARÁ NO PERÍODO DE 2019 A 2022

# Introdução

# 1.Carregando as bibliotecas

#importando as bibliotecas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm
plt.style.use ('ggplot')

# 2. Carregando Dataset

In [2]:
#lendo o arquivo csv
df= pd.read_csv("PlanilhaUnificada.csv", encoding="utf-8")

In [3]:
df.head() #para visualizar do dataframe

,AIS,Data,Hora,Dia da Semana,Gênero,Idade da Vítima,Escolaridade da Vítima,Raça da Vítima
0,AIS 10,01/01/19,00:00:00,Terça,Feminino,33,Superior Completo,Não Informada
1,AIS 11,01/01/19,00:05:00,Terça,Feminino,40,Ensino Fundamental Completo,Não Informada
2,AIS 09,01/01/19,00:30:00,Terça,Feminino,34,Ensino Médio Completo,Não Informada
3,AIS 05,01/01/19,00:30:00,Terça,Feminino,82,Alfabetizado,Não Informada
4,AIS 16,01/01/19,01:00:00,Terça,Feminino,53,Alfabetizado,Parda

In [4]:
df.info() #para obter informações do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79959 entries, 0 to 79958
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   AIS                     79959 non-null  object
 1   Data                    79959 non-null  object
 2   Hora                    79959 non-null  object
 3   Dia da Semana           79959 non-null  object
 4   Gênero                  79959 non-null  object
 5   Idade da Vítima         79959 non-null  object
 6   Escolaridade da Vítima  79959 non-null  object
 7   Raça da Vítima          79959 non-null  object
dtypes: object(8)
memory usage: 4.9+ MB

In [5]:
df.describe() #para ver um descrição mais especifica dos dados

,AIS,Data,Hora,Dia da Semana,Gênero,Idade da Vítima,Escolaridade da Vítima,Raça da Vítima
count,79959,79959,79959,79959,79959,79959,79959,79959
unique,26,1461,1367,7,2,103,10,6
top,AIS 19,01/01/19,20:00:00,Domingo,Feminino,33,Ensino Médio Completo,Não Informada
freq,11622,127,3436,15975,79952,2572,18526,58149

# 3.Limpeza e preparação dos Dados

In [6]:
# Verificando se há dados ausentes

pd.isnull("PlanilhaUnificada.csv")

False

In [8]:
#verificando se há dados duplicados
# neste caso não há, notamos pelo false, caso houvesse dados duplicados apareceria true para mais de uma coluna
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
79954    False
79955    False
79956    False
79957    False
79958    False
Length: 79959, dtype: bool

In [10]:
# Detectando e filtrando Valores Discrepantes (outliers)

# 4. Análise Univariada

# 5.Análise Bivariada

# 6. Gráfico de dispersão